language: python

cache: pip

sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null || brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi

matrix:
  include:
  - os: linux
    dist: trusty
    python: 2.7
  - os: linux
    dist: trusty
    python: 3.5
  - os: linux
    dist: trusty
    python: 3.6
  - os: linux
    dist: xenial
    python: 2.7
  - os: linux
    dist: xenial
    python: 3.5
  - os: linux
    dist: xenial
    python: 3.6
  - os: linux
    dist: xenial
    python: 3.7
  - os: linux
    dist: bionic
    python: 2.7
  - os: linux
    dist: bionic
    python: 3.5
  - os: linux
    dist: bionic
    python: 3.6
  - os: linux
    dist: bionic
    python: 3.7
  - os: osx
    language: generic
    env: TOXENV=py27
#  - os: osx
#    language: generic
#    env: TOXENV=py35
#  - os: osx
#    language: generic
#    env: TOXENV=py36
  - os: osx
    language: generic
    env: TOXENV=py37
#  - os: windows

  allow_failures:
    - os: osx

install:
  - pip install pipenv
  - pipenv install nose codecov
  - pipenv install --dev --skip-lock

script:
  nosetests

after_success:
  pipenv run codecov

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  server: https://pypi.org/legacy/
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    python: 3.7
    dist: xenial